shinyServer(function(input, output, session) {
  
  #source("server-rightsidebar.R",local = TRUE)
  source("server-inputdata.R",local = TRUE)
  source("server-pca.R",local=TRUE)
  #source("server-normalization.R",local = TRUE)
  #source("server-outliers.R",local = TRUE)
  #source("server-volcano.R",local = TRUE)
  #source("server-boxplot.R",local = TRUE)
  #source("server-density.R",local = TRUE)
  #source("server-heatmap.R",local = TRUE)
  #source("server-univariate.R",local = TRUE)
  # source("server-multivariate.R",local = TRUE)
  # source("server-cluster.R",local = TRUE)
  # source("server-correlations.R",local = TRUE)
  # source("server-featureselection.R",local = TRUE)
  # source("server-random_forest.R",local = TRUE)
  # source("server-rankprod.R",local = TRUE)
  # source("server-odds.R",local = TRUE)
}
)
